# Generated by Django 6.0.4 on 2026-04-26 10:49

import core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'форма контроля',
                'verbose_name_plural': 'Формы конроля',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('closed', 'Закрыто')], default='open', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
                ('study_form', models.CharField(choices=[('fulltime', 'Очная'), ('distance', 'Дистанционная')], default='fulltime', max_length=10, verbose_name='Форма обучения')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('forming', 'Формируется'), ('studying', 'Обучается'), ('graduated', 'Выпущена')], default='forming', max_length=10, verbose_name='Статус')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[core.validators.validate_phone], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='new', max_length=10, verbose_name='Статус')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.direction', verbose_name='Желаемое направление')),
                ('suggested_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_request', to='core.group', verbose_name='Предложенная группа')),
            ],
            options={
                'verbose_name': 'Заявка на поступление',
                'verbose_name_plural': 'Заявки на поступление',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[core.validators.validate_phone], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('status', models.CharField(choices=[('studying', 'Обучается'), ('expelled', 'Отчислен'), ('graduated', 'Выпущен')], default='studying', max_length=10, verbose_name='Статус обучения')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion_date', models.DateField(auto_now_add=True, verbose_name='Дата заключения')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('file_link', models.URLField(blank=True, verbose_name='Ссылка на файл договора')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='core.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название предмета')),
                ('hours', models.PositiveSmallIntegerField(verbose_name='Количество часов')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('control_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject', to='core.controlform', verbose_name='Форма контроля')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[core.validators.validate_phone], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('max_weekly_hours', models.PositiveSmallIntegerField(default=40, verbose_name='Макс. нагрузка (часов в нежедю)')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата приёма на работу')),
                ('status', models.CharField(choices=[('active', 'Работает'), ('fired', 'Уволен')], default='active', max_length=10, verbose_name='Статус')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='core.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Преподаватели',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('format', models.CharField(choices=[('offline', 'Очно'), ('online', 'Дистанционно')], default='offline', max_length=10, verbose_name='Формат')),
                ('classroom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Аудитория')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на видеоконференцию')),
                ('change_reason', models.TextField(blank=True, verbose_name='Причина изменения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shedules', to='core.group', verbose_name='Группа')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='core.shedule', verbose_name='Предыдущая версия')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shedules', to='core.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shedules', to='core.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Занятие в расписании',
                'verbose_name_plural': 'Расписание',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True, verbose_name='Присутствовал')),
                ('comment', models.TextField(blank=True, verbose_name='Примечание')),
                ('shedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='core.shedule', verbose_name='Занятие')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
                'unique_together': {('shedule', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_type', models.CharField(choices=[('current', 'Текущий'), ('intermediate', 'Промежуточные'), ('final', 'Итоговые')], default='current', max_length=12, verbose_name='Тип контроля')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата выставления')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Балл 1 - 5')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.group', verbose_name='Группа')),
                ('shedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='core.shedule', verbose_name='Связанное занятие')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='core.student', verbose_name='Ученик')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'unique_together': {('student', 'subject', 'control_type')},
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='core.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='core.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plans', to='core.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
                'unique_together': {('group', 'subject')},
            },
        ),
        migrations.AddIndex(
            model_name='shedule',
            index=models.Index(fields=['date', 'group'], name='core_shedul_date_523cec_idx'),
        ),
        migrations.AddIndex(
            model_name='shedule',
            index=models.Index(fields=['teacher', 'date'], name='core_shedul_teacher_87af81_idx'),
        ),
    ]
