# Generated by Django 6.0.4 on 2026-04-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_user_teacher_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shedule',
            new_name='Schedule',
        ),
        migrations.RenameIndex(
            model_name='schedule',
            new_name='core_schedu_date_a0a1c9_idx',
            old_name='core_shedul_date_523cec_idx',
        ),
        migrations.RenameIndex(
            model_name='schedule',
            new_name='core_schedu_teacher_87d56d_idx',
            old_name='core_shedul_teacher_87af81_idx',
        ),
    ]
