# Generated by Django 6.0.4 on 2026-04-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_shedule_schedule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='shedule',
            new_name='schedule',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('schedule', 'student')},
        ),
    ]
