# Generated by Django 6.0.4 on 2026-04-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_shedule_attendance_schedule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='shedule',
            new_name='schedule',
        ),
    ]
