# Generated by Django 6.0.4 on 2026-05-01 20:44

import core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_shedule_grade_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Methodologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[core.validators.validate_phone], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата приёма на работу')),
                ('status', models.CharField(choices=[('active', 'Работает'), ('fired', 'Уволен')], default='active', max_length=10, verbose_name='Статус')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='methodist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (аутентификация)')),
            ],
            options={
                'verbose_name': 'Методист',
                'verbose_name_plural': 'Методисты',
            },
        ),
    ]
